### ISSUE TITLE
Ender backpack crashes server when Create deployer interacts with it

### ISSUE THREAD

**Issue by nearbear** [SammySemicolon/Backpack-Mod#10]
The ender backpack appears to be crashing the server when a deployer from create interacts with it, I can reproduce this every time without fail. Might just need a simple existence check?

```[15Aug2021 13:58:08.544] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: No value present
	Index: 17
	Listeners:
		0: HIGHEST
		1: ASM: subaraki.paintings.event.PlacePaintingEventHandler@3099b24d onPaintingPlaced(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		2: HIGH
		3: ASM: class net.mehvahdjukaar.supplementaries.events.ServerEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		4: ASM: class tschipp.carryon.common.event.ItemEvents onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		5: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		6: ASM: tschipp.carryon.common.event.ItemEvents@eff5cfd onBlockClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		7: ASM: tschipp.carryon.common.event.ItemEntityEvents@50d8d531 onBlockClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		8: NORMAL
		9: ASM: class snownee.snow.GameEvents onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		10: ASM: class com.commodorethrawn.strawgolem.events.GolemEventHandler setPriorityChest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		11: ASM: class com.commodorethrawn.strawgolem.events.GolemCreationHandler onGolemBuiltAlternate(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		12: ASM: com.blackgear.cavesandcliffs.common.events.GlowingSignEvent@526ae8f3 onSignRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		13: ASM: net.pyromancer.procedures.PottingFadedRootsProcedure@5a015b40 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		14: ASM: class net.blazekrew.variant16x.registry.EventRegistry onRightClickedWithAxe(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		15: ASM: com.Rolfmao.upgradednetherite.handlers.EventHandler@73bbc2c6 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		16: ASM: net.pyromancer.procedures.PigmenLegionActivationProcedure@487885c5 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		17: ASM: class com.sammy.omnis_backpacks.common.events.RuntimeEvents rightClickBackpack(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		18: ASM: com.nekomaster1000.infernalexp.events.MiscEvents@61a1135c onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		19: ASM: class cech12.extendedmushrooms.ExtendedMushrooms onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		20: ASM: class com.netheragriculture.events.PlayerEvents itemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		21: ASM: class com.netheragriculture.blocks.NetherFarmlandBlock onTill(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		22: ASM: class com.netheragriculture.blocks.NetherDoublePlantBlock grow(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		23: ASM: class com.endlesnights.torchslabsmod.event.PlaceHandlerTorchWall onBlockEntityPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		24: ASM: class com.endlesnights.torchslabsmod.event.PlaceHandlerTorchSlab onBlockEntityPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		25: ASM: class com.endlesnights.torchslabsmod.event.PlaceHandlerPadLights onBlockEntityPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		26: ASM: class com.endlesnights.torchslabsmod.event.PlaceHandlerLanternWall onBlockEntityPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		27: ASM: class com.endlesnights.torchslabsmod.event.PlaceHandlerLanternSlab onBlockEntityPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		28: ASM: class com.endlesnights.torchslabsmod.event.PlaceHandlerEndRod onBlockEntityPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		29: ASM: class com.endlesnights.torchslabsmod.event.PlaceHandlerChainSlab onBlockEntityPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		30: ASM: class bl4ckscor3.mod.sit.SitHandler onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		31: ASM: com.sajevius.betterlands.procedures.JuniperLogsStrippingProcedure@5f9e2436 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		32: ASM: class com.legacy.blue_skies.events.SkiesPlayerEvents onPlayerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		33: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@1e8d8bff onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		34: net.minecraftforge.eventbus.EventBus$$Lambda$2577/1436144388@307b9237
		35: ASM: class com.cgessinger.creaturesandbeasts.common.util.ModEventHandler onBlockActivate(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		36: ASM: class vazkii.patchouli.common.handler.LecternEventHandler rightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		37: ASM: class vectorwing.farmersdelight.items.KnifeItem$KnifeEvents onCakeInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		38: ASM: class vectorwing.farmersdelight.blocks.CuttingBoardBlock$ToolCarvingEvent onSneakPlaceTool(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		39: ASM: class de.ellpeck.craftabledeeds.Events onBlockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		40: ASM: class twilightforest.TFEventListener onPlayerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		41: ASM: class net.mcreator.nourished_end.procedures.BonemealRootedEndStoneProcedure$GlobalTrigger onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		42: ASM: class com.minecraftabnormals.buzzier_bees.core.other.BBEvents renewableFlowers(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		43: ASM: class com.minecraftabnormals.environmental.core.other.EnvironmentalEvents onEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		44: ASM: class com.minecraftabnormals.savageandravage.core.other.SREvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		45: ASM: class com.lilypuree.decorative_blocks.setup.ModSetup onRightClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		46: ASM: class com.minecraftabnormals.upgrade_aquatic.core.events.EntityEvents rightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		47: ASM: class com.minecraftabnormals.abnormals_delight.core.other.ADEvents onCakeInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		48: ASM: net.mcreator.natureexpansion.procedures.PlantarYuccaPProcedure@3dbdde0d onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		49: ASM: net.mcreator.natureexpansion.procedures.PlantarBlueBerriesProcedure@448821d5 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		50: net.minecraftforge.eventbus.EventBus$$Lambda$2577/1436144388@199b77b9
		51: ASM: class com.simibubi.create.foundation.tileEntity.behaviour.linked.LinkHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		52: ASM: class com.simibubi.create.foundation.tileEntity.behaviour.filtering.FilteringHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		53: ASM: class com.simibubi.create.foundation.tileEntity.behaviour.edgeInteraction.EdgeInteractionHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		54: ASM: class com.simibubi.create.foundation.block.ItemUseOverrides onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		55: ASM: class com.simibubi.create.content.logistics.block.funnel.FunnelItem funnelItemAlwaysPlacesWhenUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		56: ASM: class com.simibubi.create.content.contraptions.components.flywheel.engine.FurnaceEngineBlock usingFurnaceEngineOnFurnacePreventsGUI(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		57: thedarkcolour.kotlinforforge.eventbus.KotlinEventBus$$Lambda$14716/1082153830@4990a1f3
		58: thedarkcolour.kotlinforforge.eventbus.KotlinEventBus$$Lambda$14716/1082153830@3073f1d8
		59: ASM: vazkii.quark.content.building.module.BurnVinesModule@2ec6eb68 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		60: ASM: vazkii.quark.content.building.module.ShallowDirtModule@35bcd3e onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		61: ASM: vazkii.quark.content.building.module.StoolsModule@783e4274 itemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		62: ASM: vazkii.quark.content.building.module.TieLeadsToFencesModule@17bca9ae onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		63: ASM: vazkii.quark.content.tweaks.module.DirtToPathModule@2b52ee53 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		64: ASM: vazkii.quark.content.tweaks.module.EnhancedLaddersModule@1afd4ab5 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		65: ASM: vazkii.quark.content.tweaks.module.ReplaceScaffoldingModule@6e10bea5 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		66: ASM: vazkii.quark.content.tweaks.module.SignEditingModule@6e6462cf onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		67: ASM: vazkii.quark.content.tweaks.module.SimpleHarvestModule@ab8be12 onClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		68: ASM: tschipp.carryon.common.capabilities.event.PositionCommonEvents@212ad87c onBlockRight(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		69: ASM: com.lothrazar.villagertools.ItemEvents@40beba7c onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		70: net.minecraftforge.eventbus.EventBus$$Lambda$2577/1436144388@5cf537cb
		71: ASM: com.teamaurora.enhanced_mushrooms.core.other.EMEvents@345b6788 rightClickBlockEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		72: ASM: svenhjol.charm.module.PathToDirt@62b7960d onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		73: LOWEST
		74: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem consumeDurabilityOnPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source)
	at com.sammy.omnis_backpacks.HiddenHelper.curiosEvent(HiddenHelper.java:54)
	at com.sammy.omnis_backpacks.common.events.RuntimeEvents.rightClickBackpack(RuntimeEvents.java:35)
	at net.minecraftforge.eventbus.ASMEventHandler_124_RuntimeEvents_rightClickBackpack_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:831)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activateInner(DeployerHandler.java:269)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activate(DeployerHandler.java:134)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerMovementBehaviour.activate(DeployerMovementBehaviour.java:89)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerMovementBehaviour.visitNewPosition(DeployerMovementBehaviour.java:70)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.tickActors(AbstractContraptionEntity.java:273)
	at com.simibubi.create.content.contraptions.components.structureMovement.gantry.GantryContraptionEntity.tickContraption(GantryContraptionEntity.java:60)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.func_70071_h_(AbstractContraptionEntity.java:239)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[15Aug2021 13:58:08.555] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID d1aafc6a-9d3d-40a5-8c2d-181902ade658
[15Aug2021 13:58:08.558] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:1.8.0_251]
	at com.sammy.omnis_backpacks.HiddenHelper.curiosEvent(HiddenHelper.java:54) ~[omnis_backpacks:1.2.1]
	at com.sammy.omnis_backpacks.common.events.RuntimeEvents.rightClickBackpack(RuntimeEvents.java:35) ~[omnis_backpacks:1.2.1]
	at net.minecraftforge.eventbus.ASMEventHandler_124_RuntimeEvents_rightClickBackpack_RightClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:831) ~[forge:?]
	at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activateInner(DeployerHandler.java:269) ~[create:mc1.16.5_v0.3.2b]
	at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activate(DeployerHandler.java:134) ~[create:mc1.16.5_v0.3.2b]
	at com.simibubi.create.content.contraptions.components.deployer.DeployerMovementBehaviour.activate(DeployerMovementBehaviour.java:89) ~[create:mc1.16.5_v0.3.2b]
	at com.simibubi.create.content.contraptions.components.deployer.DeployerMovementBehaviour.visitNewPosition(DeployerMovementBehaviour.java:70) ~[create:mc1.16.5_v0.3.2b]
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.tickActors(AbstractContraptionEntity.java:273) ~[create:mc1.16.5_v0.3.2b]
	at com.simibubi.create.content.contraptions.components.structureMovement.gantry.GantryContraptionEntity.tickContraption(GantryContraptionEntity.java:60) ~[create:mc1.16.5_v0.3.2b]
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.func_70071_h_(AbstractContraptionEntity.java:239) ~[create:mc1.16.5_v0.3.2b]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more```

**Comment by SammySemicolon** [comment]
PlacePaintingEventHandler ???
I think the issue is just, me not checking if the thing that's trying to open the backpack ui is a player ?

**Comment by nearbear** [comment]
That's just the first entry in a list of listeners, I probably didn't need to include the list. The stack trace is a little further down.

Yeah that was my impression as well, though I had trouble finding the section of code responsible for it. I can look a little closer when I get back home.
